name: Auto PR to main on new branch

on:
  push:
    branches-ignore:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
    steps:
      - name: Create Pull Request to main
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo, owner } = context.repo;
            const head = context.ref.replace('refs/heads/', '');
            const base = 'main';
            // Check if PR already exists
            const { data: pulls } = await github.rest.pulls.list({
              owner,
              repo,
              head: `${owner}:${head}`,
              base,
              state: 'open'
            });
            if (pulls.length === 0) {
              await github.rest.pulls.create({
                owner,
                repo,
                title: `Auto PR: ${head} → main`,
                head,
                base,
                body: `This pull request was automatically created when the branch \`${head}\` was pushed.`
              });
              console.log('PR created');
            } else {
              console.log('PR already exists');
            }
