name: Auto PR to main on new branch

on:
  create:

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch' && github.ref_name != 'main' && github.ref_name != 'master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          title: 'Auto PR: ${{ github.ref_name }} → main'
          body: |
            This pull request was automatically created when the branch `${{ github.ref_name }}` was created.
